### ISSUE TITLE
Структура кода

### ISSUE THREAD

**Issue by ChALkeR** [GoldenMan123/battleship#3]
https://github.com/GoldenMan123/battleship/blob/master/main.js#L160-L187 — у вас тут вложенность слишком большая, да и ниже в свитче по `req.action` слабо понятно, что происходит.

Нижний свитч можно переделать в набор функций-обработчиков (`const handlers = {}; handlers.getUsers = …`).

Например, от Promise в 54d6df6c5788aae4e2e62e2604069d6bb01e1e82 явно лучше не стало, смысл был не в этом.

В database не надо на каждый чих Promise руками создавать, есть же promisifyAll.

Плюс все остальные замечания, которые я в чате упоминал.

**Comment by GoldenMan123** [comment]
- Убрана излишняя вложенность при авторизации
- Свитч --> Набор функций
- Promise в authorize убран (откат до 3f2fe378186ccdde305260831802972499b0905d)
- Переписан http_callback

**Comment by GoldenMan123** [comment]
- database.js тоже переписан
